local JSON = [[
{
  "niveles": [
    {
      "id": 1,
      "nombre": "Nivel 1",
      "descripcion": null,
      "jugador": {
        "posicion": {
          "X": -86.595,
          "Y": 29.302,
          "Z": 266.125
        }
      },
      "vehiculo": {
        "posicion": {
          "X": -45.946,
          "Y": 27.104,
          "Z": 271.648
        },
        "orientacion": {
          "X": -92.973,
          "Y": -92.973,
          "Z": 0
        }
      },
      "pista": {
        "id": 1,
        "nombre": "Pista1",
        "posicion": {
          "X": 19.162,
          "Y": 6.93,
          "Z": -96.735
        },
        "destruibles": [
          {
            "id": 1,
            "tipo": "manzana",
            "color": "roja",
            "valor": 10,
            "posicion": {
              "X": -261.85577392578125,
              "Y": 7.114245891571045,
              "Z": -460.722900390625
            }
          },
          {
            "id": 2,
            "tipo": "manzana",
            "color": "roja",
            "valor": 10,
            "posicion": {
              "X": -270.10443115234375,
              "Y": 7.114245891571045,
              "Z": 63.99781799316406
            }
          },
          {
            "id": 3,
            "tipo": "manzana",
            "color": "roja",
            "valor": 10,
            "posicion": {
              "X": -261.85577392578125,
              "Y": 7.114245891571045,
              "Z": -305.8501281738281
            }
          },
          {
            "id": 4,
            "tipo": "manzana",
            "color": "roja",
            "valor": 10,
            "posicion": {
              "X": 126.97386169433594,
              "Y": 7.114245414733887,
              "Z": 263.31396484375
            }
          },
          {
            "id": 5,
            "tipo": "manzana",
            "color": "roja",
            "valor": 10,
            "posicion": {
              "X": 314.5657653808594,
              "Y": 7.114245891571045,
              "Z": -381.3167724609375
            }
          },
          {
            "id": 6,
            "tipo": "manzana",
            "color": "roja",
            "valor": 10,
            "posicion": {
              "X": 314.5657653808594,
              "Y": 7.114245891571045,
              "Z": -460.722900390625
            }
          },
          {
            "id": 7,
            "tipo": "manzana",
            "color": "roja",
            "valor": 10,
            "posicion": {
              "X": -13.646484375,
              "Y": 7.114245891571045,
              "Z": -460.722900390625
            }
          },
          {
            "id": 8,
            "tipo": "manzana",
            "color": "roja",
            "valor": 10,
            "posicion": {
              "X": -270.10443115234375,
              "Y": 7.114245891571045,
              "Z": 253.28939819335938
            }
          },
          {
            "id": 9,
            "tipo": "manzana",
            "color": "roja",
            "valor": 10,
            "posicion": {
              "X": -102.21490478515625,
              "Y": 7.114246368408203,
              "Z": 256.30731201171875
            }
          },
          {
            "id": 10,
            "tipo": "manzana",
            "color": "roja",
            "valor": 10,
            "posicion": {
              "X": 314.5657653808594,
              "Y": 7.114245891571045,
              "Z": 68.6832275390625
            }
          },
          {
            "id": 11,
            "tipo": "manzana",
            "color": "verde",
            "valor": 20,
            "posicion": {
              "X": -297.446044921875,
              "Y": 9.322145462036133,
              "Z": -123.39736938476562
            }
          },
          {
            "id": 12,
            "tipo": "manzana",
            "color": "verde",
            "valor": 20,
            "posicion": {
              "X": 302.6910095214844,
              "Y": 9.322145462036133,
              "Z": -473.9251708984375
            }
          },
          {
            "id": 13,
            "tipo": "manzana",
            "color": "verde",
            "valor": 20,
            "posicion": {
              "X": 225.75375366210938,
              "Y": 9.322145462036133,
              "Z": 287.7834167480469
            }
          },
          {
            "id": 14,
            "tipo": "manzana",
            "color": "verde",
            "valor": 20,
            "posicion": {
              "X": 301.5210266113281,
              "Y": 9.322145462036133,
              "Z": -150.10069274902344
            }
          },
          {
            "id": 15,
            "tipo": "manzana",
            "color": "verde",
            "valor": 20,
            "posicion": {
              "X": 32.43653106689453,
              "Y": 9.322145462036133,
              "Z": -424.1781921386719
            }
          },
          {
            "id": 16,
            "tipo": "manzana",
            "color": "verde",
            "valor": 20,
            "posicion": {
              "X": -262.06488037109375,
              "Y": 9.322145462036133,
              "Z": -488.2876281738281
            }
          },
          {
            "id": 17,
            "tipo": "manzana",
            "color": "verde",
            "valor": 20,
            "posicion": {
              "X": 34.64979553222656,
              "Y": 9.322145462036133,
              "Z": 275.7821960449219
            }
          },
          {
            "id": 18,
            "tipo": "manzana",
            "color": "verde",
            "valor": 20,
            "posicion": {
              "X": 320.4449768066406,
              "Y": 9.322145462036133,
              "Z": 263.9208068847656
            }
          }
        ]
      }
    },
    {
      "id": 2,
      "nombre": "Nivel 2",
      "descripcion": null,
      "jugador": {
        "posicion": {
          "X": -84.285,
          "Y": 32.541,
          "Z": 170.783
        },
        "orientacion": {
          "X": 0,
          "Y": 136.056,
          "Z": 0
        }
      },
      "vehiculo": {
        "posicion": {
          "X": -35.179,
          "Y": 35.577,
          "Z": 180.408
        },
        "orientacion": {
          "X": 0,
          "Y": 136.056,
          "Z": 0
        }
      },
      "pista": {
        "id": 1,
        "nombre": "PistaCircle",
        "posicion": {
          "X": 19.162,
          "Y": 16.418,
          "Z": -96.735
        },
        "destruibles": [
          {
            "tipo": "manzana",
            "id": 1,
            "valor": 10,
            "posicion": {
              "Y": 12.940889358520508,
              "X": 130.4133758544922,
              "Z": 207.7665252685547
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 2,
            "valor": 10,
            "posicion": {
              "Y": 12.940889358520508,
              "X": -75.27932739257812,
              "Z": 113.2122802734375
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 3,
            "valor": 10,
            "posicion": {
              "Y": 7.114245891571045,
              "X": 314.5657653808594,
              "Z": 68.6832275390625
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 4,
            "valor": 10,
            "posicion": {
              "Y": 12.940889358520508,
              "X": -69.89653015136719,
              "Z": 219.77589416503906
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 5,
            "valor": 10,
            "posicion": {
              "Y": 12.940889358520508,
              "X": 349.47406005859375,
              "Z": -12.669426918029785
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 6,
            "valor": 10,
            "posicion": {
              "Y": 12.940889358520508,
              "X": 275.93798828125,
              "Z": 108.82609558105469
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 7,
            "valor": 10,
            "posicion": {
              "Y": 12.940889358520508,
              "X": 210.58230590820312,
              "Z": 191.6373748779297
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 8,
            "valor": 10,
            "posicion": {
              "Y": 12.940889358520508,
              "X": -200.1829376220703,
              "Z": 5.111240386962891
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 9,
            "valor": 10,
            "posicion": {
              "Y": 12.940889358520508,
              "X": -257.07470703125,
              "Z": -140.8541259765625
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 10,
            "valor": 10,
            "posicion": {
              "Y": 12.940889358520508,
              "X": -264.0339050292969,
              "Z": 68.35111999511719
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 11,
            "valor": 10,
            "posicion": {
              "Y": 12.940889358520508,
              "X": 224.83592224121094,
              "Z": -213.68763732910156
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 12,
            "valor": 20,
            "posicion": {
              "Y": 15.148788452148438,
              "X": 249.9412384033203,
              "Z": -262.11773681640625
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 13,
            "valor": 20,
            "posicion": {
              "Y": 15.148788452148438,
              "X": -133.3262176513672,
              "Z": -376.8604431152344
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 14,
            "valor": 20,
            "posicion": {
              "Y": 15.148788452148438,
              "X": -28.4757022857666,
              "Z": -405.91876220703125
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 15,
            "valor": 20,
            "posicion": {
              "Y": 9.322145462036133,
              "X": -262.06488037109375,
              "Z": -488.2876281738281
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 16,
            "valor": 20,
            "posicion": {
              "Y": 15.148788452148438,
              "X": 118.14208221435547,
              "Z": -311.2996520996094
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 17,
            "valor": 20,
            "posicion": {
              "Y": 15.148787498474121,
              "X": 10.647466659545898,
              "Z": -349.8865051269531
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 18,
            "valor": 20,
            "posicion": {
              "Y": 15.148788452148438,
              "X": -224.20440673828125,
              "Z": -264.0470275878906
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 19,
            "valor": 20,
            "posicion": {
              "Y": 15.148788452148438,
              "X": 291.54595947265625,
              "Z": -111.44084167480469
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 20,
            "valor": 20,
            "posicion": {
              "Y": 15.148788452148438,
              "X": -107.56655883789062,
              "Z": -292.4905090332031
            },
            "color": "verde"
          }
        ]
      }
    },
    {
      "id": 3,
      "nombre": "Nivel 3",
      "descripcion": null,
      "jugador": {
        "posicion": {
          "X": -34.968,
          "Y": 58.47,
          "Z": -568.327
        },
        "orientacion": {
          "X": 0,
          "Y": 39.057,
          "Z": 0
        }
      },
      "vehiculo": {
        "posicion": {
          "X": -80.975,
          "Y": 60.073,
          "Z": -545.265
        },
        "orientacion": {
          "X": -92.973,
          "Y": -92.973,
          "Z": 0
        }
      },
      "pista": {
        "id": 1,
        "nombre": "Pista8",
        "posicion": {
          "X": 19.162,
          "Y": 62,
          "Z": -96.735
        },
        "destruibles": [
          {
            "tipo": "manzana",
            "id": 1,
            "valor": 10,
            "posicion": {
              "Y": 46.14241027832031,
              "X": -24.126571655273438,
              "Z": -165.5281524658203
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 2,
            "valor": 10,
            "posicion": {
              "Y": 46.14241409301758,
              "X": -141.42208862304688,
              "Z": -295.8401794433594
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 3,
            "valor": 10,
            "posicion": {
              "Y": 7.114245891571045,
              "X": 314.5657653808594,
              "Z": 68.6832275390625
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 4,
            "valor": 10,
            "posicion": {
              "Y": 76.24420928955078,
              "X": 98.10675048828125,
              "Z": 363.143310546875
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 5,
            "valor": 10,
            "posicion": {
              "Y": 76.24420928955078,
              "X": -144.42904663085938,
              "Z": 80.09098815917969
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 6,
            "valor": 10,
            "posicion": {
              "Y": 52.27989959716797,
              "X": 103.89898681640625,
              "Z": 5.53948974609375
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 7,
            "valor": 10,
            "posicion": {
              "Y": 46.14241027832031,
              "X": 194.6345672607422,
              "Z": -225.13372802734375
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 8,
            "valor": 10,
            "posicion": {
              "Y": 46.14241027832031,
              "X": 198.5557861328125,
              "Z": -495.6605224609375
            },
            "color": "roja"
          },
          {
            "tipo": "manzana",
            "id": 9,
            "valor": 20,
            "posicion": {
              "Y": 78.45211029052734,
              "X": 69.85508728027344,
              "Z": -128.16880798339844
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 10,
            "valor": 20,
            "posicion": {
              "Y": 78.45211029052734,
              "X": -98.10459899902344,
              "Z": 17.010467529296875
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 11,
            "valor": 20,
            "posicion": {
              "Y": 9.322145462036133,
              "X": -262.06488037109375,
              "Z": -488.2876281738281
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 12,
            "valor": 20,
            "posicion": {
              "Y": 65.64657592773438,
              "X": 127.3112564086914,
              "Z": -178.96359252929688
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 13,
            "valor": 20,
            "posicion": {
              "Y": 48.350311279296875,
              "X": 103.12300109863281,
              "Z": -594.9408569335938
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 14,
            "valor": 20,
            "posicion": {
              "Y": 48.350311279296875,
              "X": -93.12914276123047,
              "Z": -486.83575439453125
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 15,
            "valor": 20,
            "posicion": {
              "Y": 78.45211029052734,
              "X": -199.6655731201172,
              "Z": 248.0411376953125
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 16,
            "valor": 20,
            "posicion": {
              "Y": 48.350311279296875,
              "X": -164.03860473632812,
              "Z": -382.5036926269531
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 17,
            "valor": 20,
            "posicion": {
              "Y": 78.45211029052734,
              "X": 205.00668334960938,
              "Z": 248.08766174316406
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 18,
            "valor": 20,
            "posicion": {
              "Y": 78.45211029052734,
              "X": 3.5896453857421875,
              "Z": 424.1588134765625
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 19,
            "valor": 20,
            "posicion": {
              "Y": 78.45211029052734,
              "X": 27.28516387939453,
              "Z": -68.8802719116211
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 20,
            "valor": 20,
            "posicion": {
              "Y": 48.350311279296875,
              "X": 251.44058227539062,
              "Z": -332.9773254394531
            },
            "color": "verde"
          },
          {
            "tipo": "manzana",
            "id": 21,
            "valor": 20,
            "posicion": {
              "Y": 62.58372497558594,
              "X": 101.39055633544922,
              "Z": 37.47254943847656
            },
            "color": "verde"
          }
        ]
      }
    }
  ]
}
]]

return JSON
